/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouDiagnosticRouteImport } from './routes/thank-you-diagnostic'
import { Route as ThankYouChecklistRouteImport } from './routes/thank-you-checklist'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const ThankYouDiagnosticRoute = ThankYouDiagnosticRouteImport.update({
  id: '/thank-you-diagnostic',
  path: '/thank-you-diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouChecklistRoute = ThankYouChecklistRouteImport.update({
  id: '/thank-you-checklist',
  path: '/thank-you-checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/thank-you-checklist': typeof ThankYouChecklistRoute
  '/thank-you-diagnostic': typeof ThankYouDiagnosticRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/thank-you-checklist': typeof ThankYouChecklistRoute
  '/thank-you-diagnostic': typeof ThankYouDiagnosticRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/thank-you-checklist': typeof ThankYouChecklistRoute
  '/thank-you-diagnostic': typeof ThankYouDiagnosticRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/privacy'
    | '/reset-password'
    | '/thank-you-checklist'
    | '/thank-you-diagnostic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contact'
    | '/privacy'
    | '/reset-password'
    | '/thank-you-checklist'
    | '/thank-you-diagnostic'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/privacy'
    | '/reset-password'
    | '/thank-you-checklist'
    | '/thank-you-diagnostic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ThankYouChecklistRoute: typeof ThankYouChecklistRoute
  ThankYouDiagnosticRoute: typeof ThankYouDiagnosticRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you-diagnostic': {
      id: '/thank-you-diagnostic'
      path: '/thank-you-diagnostic'
      fullPath: '/thank-you-diagnostic'
      preLoaderRoute: typeof ThankYouDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you-checklist': {
      id: '/thank-you-checklist'
      path: '/thank-you-checklist'
      fullPath: '/thank-you-checklist'
      preLoaderRoute: typeof ThankYouChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ThankYouChecklistRoute: ThankYouChecklistRoute,
  ThankYouDiagnosticRoute: ThankYouDiagnosticRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
